version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '11:00'
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/functions'
    schedule:
      interval: weekly
      time: '11:00'
    open-pull-requests-limit: 10
